apiVersion: v1
appVersion: 2.0.1
description: A Helm chart to deploy Confluent Operator in Kubernetes
home: https://www.confluent.io/
keywords:
- Confluent
- Confluent Operator
- Confluent Platform
maintainers:
- email: operator@confluent.io
  name: Confluent Operator
name: confluent-for-kubernetes
sources:
- https://docs.confluent.io/current/index.html
version: 0.174.13
